### ISSUE TITLE
Framegrabber output with non power-of-two size

### ISSUE THREAD

**Issue by mrgreywater** [hyperion-project/hyperion#367] opened 2015-08-09 16:56 UTC
Setup: RPi2 outputting Adalight Protocol to Arduino driving WS2812b strips.

When setting the framegrabber width or height to non power-of-two values such as here:
```
	"framegrabber" : 
	{
		"width" : 100,
		"height" : 50,
		"frequency_Hz" : 30.0
	},
```
The positions of the colors of the LEDs will be all over the place.
When changing it to let's say
```
	"framegrabber" : 
	{
		"width" : 128,
		"height" : 64,
		"frequency_Hz" : 30.0
	},
```
everything works as expected.

If these values aren't supported, there should be either an error message in the log, or the values should be internally rounded up to the next power of two.

**Comment by brindosch** [comment] 2016-03-08 19:04
@mrgreywater I tested your values with the latest release. I could not verify this.

I will close it due to age. Just open a new one

**Comment by mrgreywater** [comment] 2016-03-08 19:07
Did you test it with a rpi2? Because I verified it multiple times, and NPOT textures are rarely supported on embedded devices.

**Comment by brindosch** [comment] 2016-03-08 19:14
Rpi3 but i used the following values on rpi2 before

`		"width" : 256,
		"height" : 144,`

I have to admit, that i use no "Adalight Protocol to Arduino". It is native with APA102. But this should not belongt to the grabber. Could you lower your frequency_Hz?

**Comment by mrgreywater** [comment] 2016-03-08 19:16
rpi3 has most likely a different graphics card that supports non power of two textures, whereas the rpi2 might not. Closing this issue is not a solution.
See https://www.opengl.org/wiki/NPOT_Texture

**Comment by brindosch** [comment] 2016-03-08 19:34
As far as i know, the Pi1/Pi2/Pi3 share the same gpu. Just some clock increase.

**Comment by brindosch** [comment] 2016-03-08 19:35
Just have a look https://en.wikipedia.org/wiki/VideoCore

**Comment by brindosch** [comment] 2016-03-08 20:04
@mrgreywater 
Could you try to connect your ws2812B strip without arduino? There is a hyperion version out there that supports rpi2 with pwm. Just to verify.
Thank you

**Comment by mrgreywater** [comment] 2016-03-08 20:08
@brindosch I just checked with glxinfo, the graphics card supports NPOT textures so I don't know... I will compile the current hyperion version tomorrow and check again, but I doubt anything changed with the issue.
I could try the strip without the arduino, but I don't know why I should... It works fine right now, it just bugs out when i change the framegrabber width/height to a npot value. I'm sure the same will happen if I connect the strip directly.

**Comment by tpmodding** [comment] 2016-03-09 22:41
we tested it, you are right. i have the same issue, but i dont think this is necessary, most of us use a POT. a note should be enough, i will add it to our todo list :) thank you!

**Comment by brindosch** [comment] 2016-06-01 21:14
@mrgreywater 
fix confirmed
will be part of V1.03.0

**Closed by brindosch** 2016-06-01 21:14 UTC
Labels: BUG
