### ISSUE TITLE
please add philipshue ledstrip "modelid": "FLS-PP3", to config

### ISSUE THREAD

**Issue by donuts11** [hyperion-project/hyperion#386] opened 2015-09-21 18:08 UTC
need this to be addet in config

"lights": {
		"4": {
			"state": {
				"on": true,
				"bri": 203,
				"hue": 8687,
				"sat": 133,
				"effect": "none",
				"xy": [
					0.389,
					0.382
				],
				"ct": 262,
				"alert": "none",
				"colormode": "ct",
				"reachable": true
			},
			"type": "Extended color light",
			"name": "Light strip tv",
			"modelid": "FLS-PP3",
			"manufacturername": "dresden elektronik",
			"uniqueid": "00:21:2e:ff:ff:00:7e:32-0a",
			"swversion": "32000079",
			"pointsymbol": {
				"1": "none",
				"2": "none",
				"3": "none",
				"4": "none",
				"5": "none",
				"6": "none",
				"7": "none",
				"8": "none"
			}
		},

and cant get hyperion to work with bulps or strip

"modelid": "FLS-PP3",
"modelid": "LCT001",

got some error

log:

Application build time: Mar  6 2015 20:57:44
QCoreApplication initialised
Selected configuration file: /etc/hyperion.config.json
ColorTransform 'default' => [0; 1]
Device configuration:
{
        "colororder" : "rgb",
        "name" : "MyPi",
        "output" : "192.168.1.14",
        "switchoffonblack" : false,
        "transitiontime" : 2,
        "type" : "philipshue",
        "username" : "05fe623b1da774ed8c9f5f9a5815583b"
}

Black border threshold set to 0.01 (3)
Not creating any smoothing
Effect loaded: Knight rider
Effect loaded: Blue mood blobs
Effect loaded: Cold mood blobs
Effect loaded: Full color mood blobs
Effect loaded: Green mood blobs
Effect loaded: Red mood blobs
Effect loaded: Warm mood blobs
Effect loaded: Rainbow mood
Effect loaded: Rainbow swirl fast
Effect loaded: Rainbow swirl
Effect loaded: Snake
Effect loaded: Strobe blue
Effect loaded: Strobe Raspbmc
Effect loaded: Strobe white
Initializing Python interpreter
hyperiond: /home/tvdzwan/hyperion/dependencies/build/jsoncpp/json_value.cpp:1136: Json::Value& Json::Value::resolveReference(const char*, bool): Assertion `type_ == nullValue || type_ == objectValue' failed.

**Comment by ntim** [comment] 2015-09-22 17:24
Do you have a backtrace? In case of an unknown model id, the code selects a default gamut.

**Comment by donuts11** [comment] 2015-09-24 16:49
backtrace?????

**Comment by ntim** [comment] 2015-09-25 06:06
You can obtain a backtrace with the Gnu Debugger. The error above only says, that some JSON value could not be obtained but I do not see which one.

**Comment by mattbrian2012** [comment] 2015-11-27 18:22
I was having this same exact issue yesterday. I am also running an FLS behind my TV. playing around in config and hue API I can get hyperion to start up without errors by just adding /api on the IP address and using the same name and username in the hue api.
 "device" :
        {
                "name"       : "hyperion_test#hyperiontest",
                "type"       : "philipshue",
                "output"     : "192.168.1.112/api",
                "username": "2e259281a651937225d3fb52508094b",
                "switchOffOnBlack" : true,
                "colorOrder" : "rgb"

However It does nothing, hyperion runs but no lights are effected, able to connect to hyperion server from my android phone, synchronizes but cannot control anything. I've played around with the  "output"     :  in the config file and I did get the lights to turn off on my TV once by using the full url of the specific light strip I wanted in the output. http://192.168.1.112/api/2e259281a651937225d3fb52508094b/lights/11

Other than that no control, I am not understanding in the config file where you specifiy which device ID you are wanting to use as I have allot of hue lights it obviously is going to work trying to make calls on all of them. how does one specify which exact device ID to use, and how would one go about troubleshooting when hyperion is running without errors but no control over devices?

does the transform id have anything to do with the device ID?

    "transform" :
                [
                        {
                                "id"   : "default",
                                "leds" : "*",
                                "hsv" :
                                {

I am running hyperion on ubuntu 14.04
trying to use with one specific hue strip.
seeing as how I got the lights to turn off when starting up hyperion im guessing it is just a matter of specifying that device either in the type, output, or id, or something else im missing.
the other thing that im confused on however is that I dont see a way to individually address the bulbs in a light strip through the api so how is it even possible that this would work at all?

cheers

**Comment by mattbrian2012** [comment] 2015-11-27 18:53
it looks like you will get that error if "output" : "192.168.1.112",
but if you simply add a / to the end it will boot up
"output" : "192.168.1.112/",

**Comment by polykoma** [comment] 2016-02-16 08:37
+1 here

Also got a fls-pp and wanna know how to make it work properly!
Thank you :)

**Comment by ntim** [comment] 2016-02-16 09:28
I cannot find the "FLS-PP3" on the list of supported devices:

http://www.developers.meethue.com/documentation/supported-lights

**Comment by brindosch** [comment] 2016-03-08 18:48
@ntim  @donuts11 
last thoughts? Should i close?

**Comment by ntim** [comment] 2016-03-09 08:04
Still waiting for a comment on the FLS-PP3. If @donuts11 or @polykoma have gamut values, I can add them to the code.

**Comment by polykoma** [comment] 2016-03-09 08:26
@ntim when you give me a hint what i need to do to provide you the information.

The fls-pp hasnt got a serial number like the hue lamps to add it manually.
But i think there must be something like an ID

**Comment by ntim** [comment] 2016-03-09 09:45
If you check the website I posted above, there are gamut values x,y for red green and blue. Those I have to add to the code to be able to compute the correct colors. 

Besides that, are the lights responding?

**Comment by brindosch** [comment] 2016-03-09 21:48
@ntim
Could have a look on this request?
https://github.com/tvdzwan/hyperion/issues/387

thank you

**Comment by polykoma** [comment] 2016-03-09 21:56
@ntim since i move my household i cant test right away for next 2 weeks.

Ahh now i got what values are needed.
But the fls_pp isnt a philips device, i will try to ask the manufacturer.

The fls pp is in most cases connected to a normal rgb strip. So maybe we couls try to test the values from a philips light with true colors like iris or smth.

**Comment by ntim** [comment] 2016-03-09 22:14
Ah ok, now I understand, will look into it tomorrow.

**Comment by polykoma** [comment] 2016-03-09 22:40
If there is a philips light with r g b diodes only (instead rgbw or mixed colour emitters like huecolor) these values would work IMHO.

Fls pp i the pure wlan controller zigbee certified
You can connect rgb and rgbw stripes.

**Comment by ntim** [comment] 2016-03-10 08:09
So lets see, adding a slash to the end of the output is no solution since it will only result in wrong urls. the problem is, that newer versions of the hue bridge give the lights arbitrary ids, whereby with the original version a consecutive numbering was guaranteed. Also see here: https://github.com/tvdzwan/hyperion/issues/506 

I will implement a feature in the code, that reads the light ids if nothing is supplied in the config file.

**Comment by ntim** [comment] 2016-03-10 08:10
#506

**Comment by ntim** [comment] 2016-03-10 08:34
Check this: https://github.com/tvdzwan/hyperion/pull/538

**Comment by ntim** [comment] 2016-03-10 08:36
As far as I understand from the documentation, the fls-pp calculates the colors itself from the received x and y colors. The gamut values depend on the leds you connect. In this case, the code assumes the widest range possible.

**Comment by polykoma** [comment] 2016-03-10 08:40
How can i get gamut values from existing stripes 
( in my case its 18x red / green / blue   superflux leds - maybe you have seen my 800 led ceiling lamp project)

**Comment by ntim** [comment] 2016-03-10 08:57
If it is not documented for your leds, then the values are probably not known. Please try if the code works now and colors come out correctly.

**Comment by tpmodding** [comment] 2016-03-11 18:51
merged, think we can close this?

**Comment by polykoma** [comment] 2016-03-13 10:11
What means merged?

I couldnt test for feedback yet.... 

Sorry githhub sometimes is weird to understand for me

**Comment by brindosch** [comment] 2016-03-13 11:23
Just update your Hyperion with the install script and report back :)

**Comment by polykoma** [comment] 2016-03-15 19:57
I hope my internet in my new flat will work soon :)
Ill report back then!

How to follow/keep an eye on this #386 ?

Anything like favorite function for it to find it again?

**Comment by brindosch** [comment] 2016-03-23 13:24
@polykoma 
Any news? :)

**Comment by brindosch** [comment] 2016-04-17 13:10
1 month gone, it may be done, if not, just open a new one

**Closed by brindosch** 2016-04-17 13:10 UTC
Labels: Feedback required
