### ISSUE TITLE
New App: Capture Windows Desktop/Programs and forward it to Hyperion!

### ISSUE THREAD

**Issue by itouch5000** [hyperion-project/hyperion#168] opened 2014-09-20 17:31 UTC
Hey,
I would like to use Hyperion with Windows. XBMC can not play 3D ISOs. I use an other program for that. Is there a possibility?

**Comment by NeoID** [comment] 2015-09-06 08:23
I'm also interested in this. If nobody has made this before, I might take a look at it. A Windows service would be awesome.

**Comment by KenV99** [comment] 2015-09-15 11:20
This works well for me on Windows if you go directly via USB to an Arduino. Takes some fiddling to get going though.
http://www.ambibox.ru/en/index.php/Main_Page

**Comment by NeoID** [comment] 2015-09-15 12:44
Thanks for the suggestion, but it sounds overly complicated. I'm also not interested in more hardware as this should be easily solved only by software (a simple Windows service). :)

**Comment by KenV99** [comment] 2015-09-15 14:08
I guess then that you want to use a USB to serial adapter to drive the LEDs directly (FTDI bitbanging)?

**Comment by NeoID** [comment] 2015-09-15 20:51
Not sure if I understand you correctly KenV99, so please let me elaborate:
I'm currently running Hyperion on my Raspberry Pi. It's only connected to power, my WS2801 LED strip and a WiFi dongle. This way I either control it using my phone or the add-on for Kodi. No wires other wires or hardware required.

So in order to get Windows supported I thought about trying to write a small service that can analyze the picture and send it to Hyperion using WiFi, just as the Kodi add-on does. I just need to figure out how the Kodi add-on is doing it and rewrite it. :)

**Comment by KenV99** [comment] 2015-09-16 17:39
I'm not sure how it's done in hyperion, but I maintain an addon for Ambibox for windows that provides screen data to the Ambibox Windows program that a different person wrote and maintains.

Addons for Kodi/XBMC are written in python. So what I do in the addon is create a memory map as a buffer and use Kodi's RenderCapture to frame grab. I then downsample and place that data in the buffer along with pixel information (RGB vs GRB, etc) and screen geometry that is then picked up by the Windows program written in C++ which translates this data and then writes to the USB port. On the Arduino there is a USB to serial FTDI chip which then provides this data to the script which then writes to the GPIO and this goes out to the LED strips.

The python code is at https://github.com/AmbiBox/kodi.script.ambibox/blob/master/default.py
The code that implements this starts at line 1038.
The api for RenderCapture is documented here: http://mirrors.kodi.tv/docs/python-docs/15.x-isengard/xbmc.html#RenderCapture

It may be that if you can provide this data via Wifi in the proper format to the v4l2 grabber routine, or some downstream portion of it, then it might be able to be used to drive the LEDs.

The author of the C++ stuff has not been willing to provide access to the code he uses.

I hope this helps. Maybe not ;)

**Comment by Fabi1080** [comment] 2015-11-09 13:40
Hyperion has several servers to listen to incoming color data. One of them is the Json server. I have written a python file to send color data to this server here: https://github.com/Fabi1080/hyperion_effects_dev_kit/blob/master/json_client.py.

So if you are able to capture the windows screen and extract the color information you just have to send it to one of hyperions servers (and they should be activated in the config file). I think Kodi uses the boblight server. But i don't know what the message format far that one is.

**Comment by NeoID** [comment] 2015-11-09 15:49
Thanks for the code snippet. I've played around with screen recording, but it's hard to capture directx/opengl applications/games.

Maybe this project would help, but sadly I don't have much time to work on this project :( http://sourceforge.net/projects/taksi/

**Comment by brindosch** [comment] 2016-03-07 23:05
@IDmedia 
Is this still in progress?

**Comment by IDmedia** [comment] 2016-03-07 23:09
@brindosch: Unfortunately... barely... I haven't had the time to work on it
much lately.

**Comment by djhansel** [comment] 2016-03-16 14:52
Hey guys, after looking all over the internet for a good solution to this, I decided to make my own. I just finished a prototype of a simple C# application that captures the screen using Direct3D9 and sends it to a Hyperion server using the JSON interface. I am finishing up some refactoring now and will be uploading it soon. The application will have a tray icon to enable/disable the capture and a standard config file to setup the IP, port, capture interval, etc. For now the capture resolution has to be very low (114x64) to be able to get good FPS, but it is not noticeable when it hits the LEDs. I should have it ready today or tomorrow. :smile:

**Comment by El-Mare** [comment] 2016-03-16 15:05
Hi djhansel,
this sounds awesome! Thanks for your efforts!
Will this work with Win 7/8.1 and 10?
Do I just need to enable the UDP listener "effect" in my RPi hosted Hyperion for this to work or is there something special about this?

**Comment by IDmedia** [comment] 2016-03-16 15:16
Awesome! I'll contribute once you've published the code. :)

**Comment by tpmodding** [comment] 2016-03-16 15:34
@El-Mare as he said he wonna use the json port :) you dont need the effect... :)

nice to hear @djhansel !! cant wait to test it :)

**Comment by El-Mare** [comment] 2016-03-16 15:39
Ah, overlooked this part ;) Even better...

**Comment by KenV99** [comment] 2016-03-16 18:17
Nice work djhansel. Since it will be sending color LED data directly from screen capture I am wondering if you were able to implement a black bar detection algorithm - something I am frequently asked about for the Kodi non-hyperion addon?

**Comment by djhansel** [comment] 2016-03-16 19:40
@KenV99 The application sends the pixel array to hyperion which already implements the black bar detection. It's similar to using the "hyperion-remote -i image.png" command, but over the JSON interface. 
@El-Mare I have only tested it on Windows 8 64-bit.

**Comment by djhansel** [comment] 2016-03-17 16:18
Hey guys,

I have published the code and a compiled version here [https://github.com/djhansel/HyperionScreenCap](https://github.com/djhansel/HyperionScreenCap)

Please feel free to fork and modify as you see fit and let me know how it works for you.

**Comment by djhansel** [comment] 2016-03-17 16:25
Just realized that embedding the SlimDX.dll in the application is not working. I am going to fix the release zip file to include the dll and remove it from the solution files.

**Comment by El-Mare** [comment] 2016-03-17 23:18
Hi djhansel,
just wanted to confirm that HyperionScreenCap works like a charm on Win7 Prof 64. I haven't experienced any delays over WiFi after fiddling a bit with the config. To get it working I downloaded the full package of DirectX9 (from chip.de), since the web installer from Microsoft didn't install anything - weird.
So, BIG THANKS for making this possible!!!

One issue though: HyperionScreenCap does not work on my Win10 Home 64 HTPC. After a few seconds the icon just disappears from tray. Any Thoughts on this one?

**Comment by djhansel** [comment] 2016-03-18 13:11
Hi @El-Mare  I am happy to hear that it works under Windows 7. I am currently installing a Windows 10 VM to find why is not working.

**Comment by brindosch** [comment] 2016-03-18 13:21
@El-Mare @djhansel 
It is working for me with Windows 10 64bit Prof.
Thank you for this great extension!
If you like, you could add it to the hyperion wiki and/or to the repo if you want. Decision is up to you.

**Comment by penfold42** [comment] 2016-03-18 13:42
I'd love to see this included - I was going to have a go at this myself

**Comment by penfold42** [comment] 2016-03-18 14:22
I cant seem to get DX9 installed on my Win7 x64 box 8-(

the "web" installer doesnt do much, and there's no way im installing a full something like DX from a non microsoft source

The old copy of DX9 from ~2002 refuses to install as theres a newer version.

I wonder if DX11 has similar APIs we can use?

**Comment by El-Mare** [comment] 2016-03-18 14:42
@penfold42 I had the same issue... just use the full package from [here](http://www.chip.de/downloads/c1_downloads_auswahl_15807515.html?t=1458311160&v=3600&s=4b9593275f8c67d7613476f27f9bac6d) (German source). This worked for me.

**Comment by djhansel** [comment] 2016-03-18 20:21
@brindosch I am okay with adding this project to the WIKI. I want to make it a bit easier to install. I will be working on creating some kind of package that will check for DirectX and install the correct version if needed, as well as, maybe putting the software in Program Data.

**Comment by penfold42** [comment] 2016-03-18 20:25
That would be brilliant !

Thanks

**Comment by djhansel** [comment] 2016-03-23 15:21
Latest version includes the installer, please let me know if it works for you guys :smile: 

https://github.com/djhansel/HyperionScreenCap/releases/tag/v1.1

**Comment by penfold42** [comment] 2016-03-24 08:01
Yep! Works great Win7 x64.

I just tested mspaint and vlc 

Can we store the config in the registry ?
Maybe a small dialing box when you right click the task bar icon ?

Thanks again, this is great

**Comment by brindosch** [comment] 2016-03-24 21:56
I tested your installer on win10 64bit. Works great!
Also i tested with Dungeons 2 (game), funny - now i need leds behind my monitor because of you!

Just one question, you need .NET 4.0 . Do you check for this too? (-> Win7 users - i forgot if this is installed by default).

Some thoughts about the location/usage.
-You could place the config in appdata in your own folder.
-A short config wizard/option page that plops up to insert the settings may be a good idea (check if the config is present in appdata, if not -> start wizard/option page on startup)
-In case the user made a mistake on setting up - add the config wizard/option page to the right click on taskbar icon, like penfold suggested.

Very good work so far

**Comment by RickDB** [comment] 2016-03-26 22:38
Tested under Windows and works like a treat :+1: 
@djhansel Awesome work!

**Comment by djhansel** [comment] 2016-03-28 14:18
Hey guys, thank you so much for the feedback so far! I am going to work on this some more this week.

For the configuration, I am planning on using the main form I already have for the tray icon and just have the config fields in there (IP, screen size, etc). The form would submit the changes and restart the connection to the new settings. Once I add this logic, it should also take care of the use case @brindosch  reported :smile: 

I am going to look into detecting the latest DirectX version installed, try to use that one and fallback to the 9 version if it fails to capture the screen.

**Comment by RickDB** [comment] 2016-03-28 14:31
SharpDX library might be a good alternative over SlimDX, did some experimenting with that library and came up with this concept grabber which supports DX 9 to 12 (hooks in to games):

https://github.com/RickDB/HyperionDX

Nowhere near finished but more of a working concept.

**Comment by brindosch** [comment] 2016-04-11 10:46
@djhansel 
I added your great work to the wiki, that every take notice of it!
Hope you find some time to include all your ideas :)
RickDB idea and dx11/12 support may great too.

**Comment by KenV99** [comment] 2016-04-11 11:21
Anyone using it with Kodi full screen, not simulated full screen? That's caused issues in the past with other capture solutions?

**Comment by RickDB** [comment] 2016-04-11 11:33
It depends on the DirectX mode for Kodi, if you use its new DX11 mode it can't hook into it.
@djhansel forked HyperionScreenCap and made a pull request, added a few new features like Protobuffer and notication levels:

https://github.com/djhansel/HyperionScreenCap/pull/7

Like mentioned there it's best to not use JSON for image sending as it's only meant for small commands, also with Protofbuffer its 1:1 bitmap exchange and only trims alpha.

**Comment by brindosch** [comment] 2016-04-11 11:40
@KenV99 
did you tried the Kodi addon? you (should) not need the full windows desktop grabber

**Comment by KenV99** [comment] 2016-04-11 12:32
I was thinking about this more as a replacement for the ambibox system in a
system where Kodi and other things (like games) are run on a Windows system
and there is an RPi not running Kodi, but running hyperion wired to an
Arduino and then the lights.
How would things work in that situation?

**Comment by RickDB** [comment] 2016-04-12 10:30
Probably not very good, for DX9 games if you keep HyperionScreenCap priority low (100) and in Kodi addon high (10) you can keep both running at the same time so can switch freely between gaming and multimedia.

However for most modern games (2012 and up) it will not work, HyperionDX does support some modern games but it comes at a performance penalty due to the nature of the hooks and can even crash games.
Best solution for games at the moment it to use live capture thru v4l2 as you just split the HDMI signal that way with no performance penalty.

**Comment by brindosch** [comment] 2016-04-12 11:03
Maybe we never get a good performance for dx10/11/12 games? I don´t like the v4l2 thing, it is so... "expensive"(from hdmi to cvbs to usb) and too much hardware if you could just grab the picture digital without any convert?

**Comment by RickDB** [comment] 2016-04-12 11:36
Yep unlikely that we ever get perfect performance with the hook methods as you either have to render twice or the game engine has to "wait" during image scan (lag / fps drops).

Live capture is actually nice once you get everything connected and calibrated but agree its a lot of hardware and work for something so simple, digital capture (HDMI <--Hyperion--> HDMI) is possible with some hardware like Auvidea is selling however it's costly and rPI support is still in the early stage (for the B101 model at least)

**Comment by djhansel** [comment] 2016-04-12 12:41
Can you guys provide me some good dx11 and dx12 applications to test capturing from them? So far I have not gotten any issues with xbmc in full screen.

**Comment by siklosi** [comment] 2016-04-25 18:34
I tried it on Win10 x64. Installed with installer, later tried installing manually all deficiencies but I always get  Failed to take screenshot.Object reference not set to an instance... d3derr_invalidcall -2005530516

**Comment by brindosch** [comment] 2016-04-26 07:23
@siklosi 
Could you retry after installing this? https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by siklosi** [comment] 2016-04-26 08:35
I already tried, but tried it again now and same error.... I was thinking that maybe its because of graphics card (integrated Intel HD 3000 on Lenovo IdeaCentre Q190)

**Comment by brindosch** [comment] 2016-04-28 07:57
May be possible. Due to the point i also use windows 10 64bit it can´t be the cause

**Comment by brindosch** [comment] 2016-04-29 20:23
Hyperion have a new home!
Please read the announcement post and the changelog for V1.02.0
www.hyperion-project.org

Please have a look at our new wiki! (EN/DE)
wiki.hyperion-project.org

All discussions/questions/development threads should be moved to the new forum!
We will close this issue now

**Closed by brindosch** 2016-04-29 20:23 UTC
Labels: enhancement, WIP

**Comment by ricardona** [comment] 2016-05-02 22:13
@siklosi I have the same error, did you resolved the problem?

tks
